### ISSUE TITLE
[Feature] @vuepress+client@2.0.0-rc.7

### ISSUE THREAD

**Issue by Paper-Dragon** [azat-io/vuepress-plugin-umami-analytics#4]

**Comment by azat-io** [comment]
Blocked by https://github.com/vuepress/core/issues/1495

**Comment by Mister-Hope** [comment]
You can always use an `as ClientConfig` to bypass it. this only happens under ts with pnpm, and probably not our own issue.

**Comment by azat-io** [comment]
Released in [v1.9.0](https://github.com/azat-io/vuepress-plugin-umami-analytics/releases/tag/v1.9.0)
